let activities = [
  {
    id: 0,
    photo:
      "https://cdn.pixabay.com/photo/2018/11/17/22/15/trees-3822149_960_720.jpg",
    idTheme: 3,
    date: "Fevereiro",
    begin: "20230201",
    end: "20230228",
    desc1: "Falta de zonas de sombra",
    desc2: "Criação de zonas de sombra",
    desc3: "Plantação de 30 árvores no Campus2",
    title: "Plantação de árvores no Campus2",
    coordinator: "admin@gmail.com",
    place: "Campus 2",
    users: [],
    participated: [],
  },
  {
    id: 1,
    photo:
      "https://cdn.pixabay.com/photo/2015/05/31/11/24/tap-791172_960_720.jpg",
    idTheme: 0,
    date: "Maio",
    begin: "20230501",
    end: "20230531",
    desc1: "Excesso de água dispendida em tarefas domésticas",
    desc2:
      "Sensibilizar a comunidade escolar para a necessidade de poupar água",
    desc3:
      "Divulgação, nas redes sociais, de informação de sensibilização para a poupança de água",
    title: "Sensibilização para poupança de água",
    coordinator: "admin@gmail.com",
    place: "Redes Sociais",
    users: [],
    participated: [],
  },
  {
    id: 2,
    photo:
      "https://cdn.pixabay.com/photo/2018/05/10/09/12/water-3387105_960_720.jpg",
    idTheme: 0,
    date: "Janeiro",
    begin: "20230101",
    end: "20230131",
    desc1: "necessidade de regar árvores",
    desc2: "criar sistema de rega para as árvores",
    desc3: "Cada árvore dispor de um dispensador de água",
    title: "Dispensadores de água para árvores",
    coordinator: "admin@gmail.com",
    place: "Campus 2",
    users: [],
    participated: [],
  },
  {
    id: 3,
    photo:
      "https://cdn.pixabay.com/photo/2012/03/04/00/52/battery-22119_960_720.jpg",
    idTheme: 1,
    date: "Maio",
    begin: "20230501",
    end: "20230531",
    desc1: "Falta de local para colocação de pilhas para reciclagem",
    desc2:
      "Contribuir para a reciclagem de resíduos particularmente agressivos para o ambiente; Estimular estudantes e docentes a colocar as suas pilhas e baterias no recipiente próprio.",
    desc3: "Colocação de pilhão na escola",
    title: "Pilhão",
    coordinator: "admin1@gmail.com",
    place: "Campus 2",
    users: [],
    participated: [],
  },
  {
    id: 4,
    photo:
      "https://images.unsplash.com/photo-1604187351574-c75ca79f5807?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80",
    idTheme: 1,
    date: "20/01/2023",
    begin: "20230120",
    end: "20230120",
    desc1:
      "Ausência de ponto de reciclagem de papel junto à Assoc. de Estudantes",
    desc2: "Promover a reciclagem de papel",
    desc3: "Colocação de ecoponto de papel junto à AEESMAD",
    title: "Ecoponto",
    coordinator: "user@gmail.com",
    place: "Campus 2",
    users: [],
    participated: [],
  },
  {
    id: 5,
    photo:
      "https://cdn.pixabay.com/photo/2017/08/20/20/20/lamp-2663053_960_720.jpg",
    idTheme: 2,
    date: "Maio",
    begin: "20230501",
    end: "20230531",
    desc1: "Zonas da escola com lâmpadas de consumo elevado de energia",
    desc2: "Redução do consumo elétrico da ESMAD",
    desc3: "Substituição lâmpadas por LED",
    title: "Substituição lâmpadas por LED",
    coordinator: "user@gmail.com",
    place: "Campus 2",
    users: [],
    participated: [],
  },
  {
    id: 6,
    photo:
      "https://cdn.pixabay.com/photo/2019/03/30/01/41/garbage-4090382_960_720.jpg",
    idTheme: 3,
    date: "Maio",
    begin: "20230501",
    end: "20230531",
    desc1: "Falta de local para colocação de lixo nas zonas ajardinadas",
    desc2:
      "Contribuir para a limpeza dos espaços exteriores e estimular a utilização das zonas ajardinadas",
    desc3: "Colocação de 10 caixotes do lixo nas zonas relvadas da ESMAD",
    title: "Colocação de caixotes do lixo",
    coordinator: "admin@gmail.com",
    place: "Campus 2",
    users: [],
    participated: [],
  },
  {
    id: 7,
    photo:
      "https://cdn.pixabay.com/photo/2015/11/01/21/19/sea-1017596_960_720.jpg",
    idTheme: 4,
    date: "26/05/2023",
    begin: "20230526",
    end: "20230526",
    desc1:
      "Falta de consciência que o lixo que é atirado para o chão, vai parar ao mar",
    desc2:
      "Consciencializar a comunidade para a importância de não atirar lixo para o chão",
    desc3: "Pintura de sargetas na zona exterior da ESMAD",
    title: "O mar começa aqui",
    coordinator: "admin@gmail.com",
    place: "Campus 2",
    users: [],
    participated: [],
  },
  {
    id: 8,
    photo:
      "https://cdn.pixabay.com/photo/2016/11/03/15/27/socket-1794616_960_720.jpg",
    idTheme: 2,
    date: "Maio e Junho",
    begin: "20230501",
    end: "20230630",
    desc1: "Equip. eletrónicos colocados em stand-by",
    desc2: "Desligar equipamentos eletrónicos",
    desc3:
      "Divulgação, nas redes sociais, de informação de sensibilização para a poupança de energia",
    title: "Sensibilização para poupança de energia em casa",
    coordinator: "admin2@gmail.com",
    place: "Redes Sociais",
    users: [],
    participated: [],
  },
  {
    id: 9,
    photo:
      "https://images.unsplash.com/photo-1613759007428-9d918fe2d36f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80",
    idTheme: 6,
    date: "Maio e Junho",
    begin: "20230501",
    end: "20230630",
    desc1: "Necessidade de posters de divulgação e sensibilização",
    desc2: "Criar posters de divulgação e sensibilização",
    desc3: "Posters de divulgação e sensibilização",
    title: "Concurso Eco-cartazes 2022",
    coordinator: "admin1@gmail.com",
    place: "Campus 2",
    users: [],
    participated: [],
  },
  {
    id: 10,
    photo:
      "https://cdn.pixabay.com/photo/2014/05/21/15/17/bicycles-349788_960_720.jpg",
    idTheme: 5,
    date: "Junho",
    begin: "20230601",
    end: "20230630",
    desc1:
      "Insuficiência de parques de estacionamento de bicicletas no exterior",
    desc2:
      "Estimular a utilização de veículos não poluentes para aceder ao recinto escolar",
    desc3:
      "Colocação de mais 20 lugares de estacionamento de bicicletas no exterior",
    title: "BiciPark Outdoor",
    coordinator: "admin@gmail.com",
    place: "Câmara Municipal",
    users: [],
    participated: [],
  },
  {
    id: 11,
    photo:
      "https://cdn.pixabay.com/photo/2021/11/21/14/50/bicycles-6814379_960_720.jpg",
    idTheme: 5,
    date: "Junho",
    begin: "20230601",
    end: "20230630",
    desc1: "Ausência de espaços cobertos para estacionar bicicletas.",
    desc2:
      "Estimular a utilização de veículos não poluentes para aceder ao recinto escolar",
    desc3: "Colocação de parque para 10 a 15 bicicletas na garagem coberta",
    title: "BiciPark Indoor",
    coordinator: "admin2@gmail.com",
    place: "Campus 2",
    users: [],
    participated: [],
  },
  {
    id: 12,
    photo:
      "https://cdn.pixabay.com/photo/2018/05/12/02/05/wooden-bench-3392273_960_720.jpg",
    idTheme: 3,
    date: "Junho e Julho",
    begin: "20230601",
    end: "20230731",
    desc1: "Falta de bancos",
    desc2: "Reutilização de paletes para criar bancos de jardim",
    desc3: "Criação de bancos",
    title: "Bancos de Jardim",
    coordinator: "admin2@gmail.com",
    place: "Campus 2",
    users: [],
    participated: [],
  },
  {
    id: 13,
    photo:
      "https://cdn.pixabay.com/photo/2014/07/30/22/53/notebook-405755_960_720.jpg",
    idTheme: 6,
    date: "Julho",
    begin: "20230701",
    end: "20230731",
    desc1:
      "Necessidade de divulgar o projecto e incentivar os alunos a participar",
    desc2: "Sensibilizar a comunidade escolar para o projecto Eco-Escolas",
    desc3: "Divulgar o projecto",
    title: "Divulgação do projecto",
    coordinator: "admin1@gmail.com",
    place: "Campus 2",
    users: [],
    participated: [],
  },
  {
    id: 14,
    photo:
      "https://cdn.pixabay.com/photo/2020/03/09/04/25/beach-4914403_960_720.jpg",
    idTheme: 4,
    date: "18/07/2023",
    begin: "20230718",
    end: "20230718",
    desc1: "Lixo nas praias",
    desc2: "Limpeza",
    desc3: "deixar a praia limpa",
    title: "Limpeza praia + separação resíduos",
    coordinator: "user@gmail.com",
    place: "Praia",
    users: [],
    participated: [],
  },
];

// let types = [
//   {
//     id: 0,
//     name: "Lâmpada fundida",
//   },
//   {
//     id: 1,
//     name: "Torneira a pingar",
//   },
//   {
//     id: 2,
//     name: "Luz ligada",
//   },
//   {
//     id: 3,
//     name: "Objeto quebrado",
//   },
//   {
//     id: 4,
//     name: "Malfuncionamento",
//   },
//   {
//     id: 5,
//     name: "Lixo no chão",
//   },
//   {
//     id: 6,
//     name: "Outro",
//   },
// ];

module.exports = activities;
