let missions = [
  {
    id: 0,
    title: "Inscreve-te na tua primeira atividade",
    description:
      "Escolhe uma atividade que gostavas de participar do plano de atividades e inscreve-te!",
    reward: "/src/assets/images/inscrever_1.png",
    users: [],
    max: 1,
    redirect: "/Activities",
    type: 0,
  },
  {
    id: 1,
    title: "Inscreve-te em 5 atividade",
    description:
      "Escolhe uma atividade que gostavas de participar do plano de atividades e inscreve-te!",
    reward: "/src/assets/images/inscrever_5.png",
    users: [],
    max: 5,
    redirect: "/Activities",
    type: 0,
  },
  {
    id: 2,
    title: "Inscreve-te em 10 atividade",
    description:
      "Escolhe uma atividade que gostavas de participar do plano de atividades e inscreve-te!",
    reward: "/src/assets/images/inscrever_10.png",
    users: [],
    max: 10,
    redirect: "/Activities",
    type: 0,
  },
  {
    id: 3,
    title: "Inscreve-te em todas as atividade",
    description:
      "Escolhe uma atividade que gostavas de participar do plano de atividades e inscreve-te!",
    reward: "/src/assets/images/inscrever_15.png",
    users: [],
    max: 15,
    redirect: "/Activities",
    type: 0,
  },
  {
    id: 4,
    title: "Participa na tua primeira atividade",
    description:
      "Depois de te insceveres numa atividade é sempre boa prática estares presente e participares na data!",
    reward: "/src/assets/images/participar_1.png",
    users: [],
    max: 1,
    redirect: "/Activities",
    type: 1,
  },
  {
    id: 5,
    title: "Participa em 5 atividades",
    description:
      "Depois de te insceveres numa atividade é sempre boa prática estares presente e participares na data!",
    reward: "/src/assets/images/participar_5.png",
    users: [],
    max: 5,
    redirect: "/Activities",
    type: 1,
  },
  {
    id: 6,
    title: "Participa em 10 atividades",
    description:
      "Depois de te insceveres numa atividade é sempre boa prática estares presente e participares na data!",
    reward: "/src/assets/images/participar_10.png",
    users: [],
    max: 10,
    redirect: "/Activities",
    type: 1,
  },
  {
    id: 7,
    title: "Participa em todas as atividades",
    description:
      "Depois de te insceveres numa atividade é sempre boa prática estares presente e participares na data!",
    reward: "/src/assets/images/participar_15.png",
    users: [],
    max: 15,
    redirect: "/Activities",
    type: 1,
  },
  {
    id: 8,
    title: "Faz a tua primeira ocorrência",
    description:
      "Verifica se há algo de errado na tua escola e faz uma ocorrência!",
    reward: "/src/assets/images/registar_ocorrencia.png",
    users: [],
    max: 1,
    redirect: "/Occurrence",
    type: 2,
  },
  {
    id: 9,
    title: "Recebe 10 pontos",
    description:
      "Ganha pelo menos 10 pontos fazendo ocorrências, participando em atividades, entrando na conta cada dia ou completando missoes!",
    reward: "/src/assets/images/10_pontos.png",
    users: [],
    max: 10,
    redirect: "/Activities",
    type: 3,
  },
  {
    id: 10,
    title: "Recebe 20 pontos",
    description:
      "Ganha pelo menos 20 pontos fazendo ocorrências, participando em atividades, entrando na conta cada dia ou completando missoes!",
    reward: "/src/assets/images/20_pontos.png",
    users: [],
    max: 20,
    redirect: "/Activities",
    type: 3,
  },
  {
    id: 11,
    title: "Inscreve-te no conselho Eco-escolas",
    description: "Inscreve-te no conselho Eco-escolas",
    reward: "/src/assets/images/inscrever_conselho.png",
    users: [],
    max: 1,
    redirect: "/Home",
    type: 4,
  },
  {
    id: 12,
    title: "Faz login todos os dias durante uma semana",
    description: "Faz login todos os dias durante uma semana",
    reward: "/src/assets/images/loginbonus.png",
    users: [],
    max: 7,
    redirect: "/Home",
    type: 6,
  },
  {
    id: 13,
    title: "Edita o teu perfil",
    description: "Edita o teu perfil",
    reward: "/src/assets/images/editar_perfil.png",
    users: [],
    max: 1,
    redirect: "/Profile",
    type: 7,
  },
  {
    id: 14,
    title: "Chega ao top 3 do quadro de líderes",
    description: "Chega ao top 3 do quadro de líderes",
    reward: "/src/assets/images/3rd_place.png",
    users: [],
    max: 3,
    redirect: "/Home",
    type: 8,
  },
  {
    id: 15,
    title: "Chega ao top 2 do quadro de líderes",
    description: "Chega ao top 2 do quadro de líderes",
    reward: "/src/assets/images/2nd_place.png",
    users: [],
    max: 2,
    redirect: "/Home",
    type: 8,
  },
  {
    id: 16,
    title: "Chega ao top 1 do quadro de líderes",
    description: "Chega ao top 1 do quadro de líderes",
    reward: "/src/assets/images/1st_place.png",
    users: [],
    max: 1,
    redirect: "/Home",
    type: 8,
  },
  {
    id: 17,
    title: "Completa todas as missões",
    description: "Completa todas as missões",
    reward: "/src/assets/images/completar_tudo.png",
    users: [],
    max: 17,
    redirect: "/Missions",
    type: 9,
  },
];

module.exports = missions;
